### ISSUE TITLE
Include @babel/plugin-transform-runtime by default

### ISSUE THREAD

**Issue by adambrgmn** [swashata/wp-webpack-script#479] opened 2019-04-30 07:43 UTC
Hi,
First, thanks for a great tool – a lifesaver!

But I've encountered the not so uncommon `Uncaught ReferenceError: regeneratorRuntime is not defined`-error while writing `async/await` code.

It's not a big issue in itself – I was able to solve it with a custom `babel.config.js` according to your [instructions](https://wpack.io/tutorials/adding-custom-babel-config/) (though  `jsBabelPresetOptions` and `jsBabelOverride` doesn't seem to be applied, but that's probably a separate issue).

I've made a repo reconstructing my issue and solution [here](https://github.com/adambrgmn/wpackio-repro) (in that repo you can also see that `jsBabelPresetOptions` and `jsBabelOverride` doesn't get applied).

I just needed to add `@babel/plugin-transform-runtime` to the list of plugins and the problem was solved.

Therefore this is not as much an issue as it is a question – what do you think about adding `@babel/plugin-transform-runtime` to `@wpackio/babel-preset-base` by default?

My suggestion is to use something similar to what [`create-react-app` is doing in their preset](https://github.com/facebook/create-react-app/blob/4b8b38bf7c55326f8d51ea9deeea76d7feee307d/packages/babel-preset-react-app/create.js#L169).

I would be happy to support with a PR if you're interested, even though I'll have to get acquainted with the code first 😄.

**Comment by swashata** [comment] 2019-04-30 08:32
Hello,

First of all thank you for giving the feedback and investigating on this issue. When I was working on the last release, the `transform-runtime` did came to my mind. But I had another pressing issue at hand (improving typescript typecheck performance), so I didn't look much into it.

So I am super glad that you brought this up and yes, please send me a PR with the changes you think would be useful (i.e, adding `@babel/plugin-transform-runtime` and `@babel/runtime` to `@wpackio/babel-preset-base`.)

Also

<blockquote>It's not a big issue in itself – I was able to solve it with a custom babel.config.js according to your instructions (though jsBabelPresetOptions and jsBabelOverride doesn't seem to be applied, but that's probably a separate issue).

I've made a repo reconstructing my issue and solution here (in that repo you can also see that jsBabelPresetOptions and jsBabelOverride doesn't get applied).</blockquote>

Maybe the doc is a bit misleading, but when you use your own babel config, then the system completely bypasses all js and ts related babel configuration.

**Comment by swashata** [comment] 2019-04-30 08:45
Also can you please confirm that if this works?

```js
const pkg = require('./package.json');

module.exports = {
  // ...
  // Keep babel config to false, turn it on if you want the system to
  // catch babel.config.js for overall replacement
  useBabelConfig: false,
  // The below is meant to be passed as options for @wpackio/babel-preset-base
  // so obviously it won't work
  jsBabelPresetOptions: {
    plugins: ['@babel/plugin-transform-runtime'],
  },
  // This should work now
  jsBabelOverride: defaults => {
    return { ...defaults, plugins: ['@babel/plugin-transform-runtime'] };
  },
  // ...
};
```

**Comment by adambrgmn** [comment] 2019-04-30 09:17
I'll be happy to look into a PR to add the runtime plugin! I'll probably get something going later this week (a holiday is coming up here in Sweden 😄).


Regarding
> Also can you please confirm that if this works?
> 
> ```js
> const pkg = require('./package.json');
> 
> module.exports = {
>   // ...
>   // Keep babel config to false, turn it on if you want the system to
>   // catch babel.config.js for overall replacement
>   useBabelConfig: false,
>   // The below is meant to be passed as options for @wpackio/babel-preset-base
>   // so obviously it won't work
>   jsBabelPresetOptions: {
>     plugins: ['@babel/plugin-transform-runtime'],
>   },
>   // This should work now
>   jsBabelOverride: defaults => {
>     return { ...defaults, plugins: ['@babel/plugin-transform-runtime'] };
>   },
>   // ...
> };
> ```

The docs ain't fuzzy on that point, I have tried with `useBabelConfig: false` as well.
But the strange thing is that I can't get that to work either. I've tried with `useBabelConfig: false` and all possible combinations of `jsBabelPresetOptions` and `jsBabelOverride`. As you can see in my repro I've [even thrown in an Error](https://github.com/adambrgmn/wpackio-repro/blob/928dfa6ad65251bf3378ee4024c843d5d71d25e6/wpackio.project.js#L34), but it doesn't throw 🤔 even with `useBabelConfig: false`.

I'm not really acquainted with where the config gets defined, but I might look into that one as well later! It's not a stressing issue since the custom `babel.config.js` works fine.

**Comment by swashata** [comment] 2019-04-30 09:37
> As you can see in my repro I've even thrown in an Error, but it doesn't throw 🤔 even with useBabelConfig: false.

Then it is indeed an error. I have some pressing work at my disposal, so maybe we can come back at it after a week or so.

**Comment by adambrgmn** [comment] 2019-05-02 07:05
As you might have noticed I've provided a PR (#483) to add the runtime plugin.
But I just want to mention that the issue with the babel overrides not being applied is probably solved – I found out that it was an "issue" with caching...

I didn't change the source code between build scripts and therefore babel didn't bother to process that file again. Once I changed the source the overrides were applied.

So no need to worry about that anymore 😄

**Comment by swashata** [comment] 2019-05-04 02:23
Hey @adambrgmn, thanks for the PR. I have merged and published in version 3.4. Also glad to know that there isn't an issue with the babel config options 👍.

You did a wonderful job on the PR. Do let me know if you'd like to be a collaborator in this repo 😃

**Comment by swashata** [comment] 2019-05-04 03:05
Looks like there is a regression.

1. We pass `noRuntime` with defaulting to `false` to `nmJsRules` (node_modules transpile).
2. It has default `useESModules` to `true`.
3. It fails for most of the npm packages, because those are CJS, not ESModules.

Hence it throws errors like 

```
./src/app/admin/components/AppWrap/index.tsx
Attempted import error: '@rehooks/component-size' does not contain a default export (imported as'useComponentSize').
 @ ./src/app/admin/screens/index.tsx
 @ ./src/app/admin/index.tsx
 @ multi ./src/app/admin/index.tsx webpack-hot-middleware/client?path=__wpackio&name=admin&dynamicPublicPath=true&overlay=true&reload=true&overlayStyles=%7B%22zIndex%22%3A999999999%2C%22fontSize%22%3A%2214px%22%2C%22fontFamily%22%3A%22Dank%20Mono%2C%20Operator%20Mono%20SSm%2C%20Operator%20Mono%2C%20Menlo%2C%20Consolas%2C%20monospace%22%2C%22padding%22%3A%2232px%2016px%22%7D
```

Possible solutions

1. Pass `noRuntime` as `true` for `nmJsRules`.
2. Maybe use `useESModules` as `false` for `nmJsRules`.

@adambrgmn do you know what CRA is doing?

**Comment by swashata** [comment] 2019-05-04 03:07
Also by looking at CRA source code, having `useESModules` always set to true will cause `jest` to fail. So I think we need a fallback here.

**Comment by swashata** [comment] 2019-05-04 03:37
Looks like I got it to solve by adding `sourceType: 'unambiguous'` to babel config of `nmJsRules` per [this comment](https://github.com/webpack/webpack/issues/4039#issuecomment-419284940)

**Comment by swashata** [comment] 2019-05-04 04:41
Hopefully release 3.5.0 resolves this.

**Closed by swashata** 2019-05-04 04:41 UTC
Labels: Priority: Medium, Status: PR Welcome, Type: Feature
